version: '2'
services:
  store:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data
    command: "true"
  postgres:
    image: postgres:latest
    volumes_from:
      - store
  go:
    build: .
    command: bash -c ". .env && app"
    links:
      - postgres:db
