version: '3'
services:
  app:
    build: .
    command: app
    depends_on:
      - postgres
    env_file: .env.docker
    image: app
    volumes:
      - .:/app
  postgres:
    image: postgres:latest
    ports:
      - '5432'
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
volumes:
  gem_cache:
